---
title: "Codebook for Maryland Poison Center (MPC) data"
author: "Leah Jager"
date: "6/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


* `fileNo` : id number for county/year combination
* `County` : county name, from 24 Maryland county (or county equivalents)
* `Year` : year, from 2006-2018
* `Totalhumanexposures` : total number of human exposures
* `AnimalExposures` : total number of animal exposures
* `InformationCalls` : total number of information calls
* `Age_Under12mo` : number of exposures for children under 12 months of age
* `Age_1yr` : number of human exposures for children aged 1 year
* `Age_2yr` : number of human exposures for children aged 2 years
* `Age_3yr` : number of humanexposures for children aged 3 years
* `Age_4yr` : number of human exposures for children aged 4 years
* `Age_5yr` : number of human exposures for children aged 5 years
* `Age_6-12yr` : number of human exposures for children aged 6 through 12 years
* `Age_13-19yr` : number of human exposures for children aged 13 through 19 years
* `Age_20-59yr` : number of human exposures for adults aged 20 through 59 years
* `Age_Over60yr` : number of human exposures for adults 60 years or older
* `Age_Adult` : number of human exposures for adults (older than 19)
* `Age_Unknown` : number of human exposures with unknown age
* `Age_UnknownAdult` : number of human exposures for adult (older than 19) with unknown age
* `Age_UnknownChild` : number of human exposures for child (19 or younger) with unknown age
* `Intentional` : number of intentional human exposures
* `Intentional_Abuse` : number of intentional human exposures
* `Intentional_Misuse` 
* `Intentional_SuspectedSuicide` 
* `Intentional_Unknown`
* `ManageSite_HealthcareFacility` 
* `ManageSite_OnSite.NonHealthcareFacility` 
* `ManageSite_Other.Unknown` 
* `ManageSite_RefusedReferral` 
* `MedOutcome_Death` 
* `MedOutcome_MajorEffect` 
* `MedOutcome_MinorEffect` 
* `MedOutcome_ModerateEffect` 
* `MedOutcome_NoEffect` 
* `MedOutcome_Other.Unknown` 
* `OtherReason` 
* `Other_AdverseReaction.Drug` 
* `Other_AdverseReaction.Food` 
* `Other_AdverseReaction.Other` 
* `Other_Contamination.Tampering` 
* `Other_Malicious` 
* `Other_Other.Unknown` 
* `Other_Withdrawal` 
* `Unintentional` 
* `Unintentional_Bite.Sting` 
* `Unintentional_Environmental` 
* `Unintentional_FoodPoisoning` 
* `Unintentional_General` 
* `Unintentional_Misuse` 
* `Unintentional_Occupational` 
* `Unintentional_Other.Unknown` 
* `Unintentional_TherapeuticError`
